### ISSUE TITLE
Instructions for building a manual release

### ISSUE THREAD

**Issue by ivan-mogilko** [adventuregamestudio/ags-manual#136]
Unfortunately every time I'm trying to publish a release in the manual I got confused about how to do that.

What are the steps required to 
* get manual assets uploaded to the release, and
* manual updated on github.io?

May this information be added to a repository's readme?

**Comment by ericoporto** [comment]
I need to think if there's anything more but below and do a step by step, are the two things I can think now:

**Approving links**

If a link to a URL that is not a manual page is added in the GitHub wiki, this means any website links but also special URLs like `mailto:`, it needs to be approved or the build process will fail. Approved links are alphabetically ordered in [`meta/approved_links.txt`](https://github.com/adventuregamestudio/ags-manual/blob/master/meta/approved_links.txt).

**Generating a release**

Just create a new tag in GitHub release interface with a name that begins with `v` (e.g. `v1.2.3`) and the GitHub Actions should trigger and generate the appropriate packages and push as assets in the Release page. The CI from ags will then pick up the most recent version of the `ags-help.chm` uploaded to a release.


@ivan-mogilko you named the tag without the beginning `v` this is why it didn't pushed to release.

**Comment by ivan-mogilko** [comment]
I relied on previous tags which were without "v", is this a new requirement or previous releases were created differently?

**Comment by ericoporto** [comment]
It's a change from when the manual migrated to using GitHub Actions (previous versions were using a different build system). @morganwillcock made the change during the transition, but I don't know the reason why, guess it was some way to not trigger releases from pushes to the gh-pages or master branch, but not sure.

**Comment by ivan-mogilko** [comment]
To clarify, #137 was closed because it was resolved, or because it was not fixable at the moment?

**Comment by ericoporto** [comment]
Sorry, should have mentioned. It was resolved! I was going to add the instructions to the README but I forgot.

**Comment by ericoporto** [comment]
Added instructions in the README: https://github.com/adventuregamestudio/ags-manual/blob/master/README.md#creating-a-release

**Comment by ivan-mogilko** [comment]
Thank you.

**Comment by ivan-mogilko** [comment]
I had to reopen this, because something is still not clear to me.

I just tried making a new release, but the resulting CHM (and the web version) appear to not have new changes from the wiki pages.

Unfortunately the link posted by @ericoporto above is no longer valid (such section does not exist in the README.md).
I found something in CONTRIBUTING.md though: https://github.com/adventuregamestudio/ags-manual/blob/master/CONTRIBUTING.md#update-the-wiki-content

I'd like to clarify - is following above instructions (cloning repo, launching some tools etc) necessary to make a release with updated CHM/web pages, or there's some kind of more automated option?

**Comment by ivan-mogilko** [comment]
Alright, so, it seems like only the first step of these instructions is necessary, where you update the "source" submodule and push the commit. At least it builds a CHM with updated content now.

One thing that bothers me is that `ags-manual-0.x.x.tar.gz` still has the previous version numbers (but the contents seem up to date).

**Comment by morganwillcock** [comment]
The updated instructions are here:
https://github.com/adventuregamestudio/ags-manual/blob/master/CONTRIBUTING.md#creating-releases

**Comment by morganwillcock** [comment]
To be more specific, you must increase the version number used in the packaging to match the release that you are making, as described in the instructions.

> Firstly verify the package version currently defined by the build system:
>
> grep ^AC_INIT configure.ac
>
>...which will give output similar to:
>
>AC_INIT([ags-manual], [1.2.3])
>
> This defines the package name and version. If the version needs to be increased edit the number and push the changes back before doing anything else.

**Comment by ivan-mogilko** [comment]
Oh sorry, I will do this next time.

Do i modify it by hand now?

**Comment by ericoporto** [comment]
@morganwillcock this means a release for EACH patch version of AGS?

**Comment by ivan-mogilko** [comment]
>  this means a release for EACH patch version of AGS?

From what I understand, this means any new release of the manual, regardless of whether it's meant for particular release of AGS or not.
I did not realize at first, but now the archived sources have a number that you have to adjust.

I.e. if you look at [0.6.5](https://github.com/adventuregamestudio/ags-manual/releases/tag/v0.6.5) the archive was called ags-manual-wiki-md-source.zip
but since [0.6.6](https://github.com/adventuregamestudio/ags-manual/releases/tag/v0.6.6) it is ags-manual-0.6.6.tar.gz.
so now it has a number linked to the manual tag number.

**Comment by morganwillcock** [comment]
> Do i modify configure.ac by hand now?

Yes, it just needs to match whatever the manual will be released as. That version represents the combination of the build system state and the wiki pages that are referenced in the sub-module - within the archive is what is needed to build as well as the wiki pages.

**Comment by morganwillcock** [comment]
> @morganwillcock this means a release for EACH patch version of AGS?

If you want to update the manual for each patch version of AGS, yes.

**Comment by ericoporto** [comment]
Ah, not the version of AGS, right? I misread...

**Comment by morganwillcock** [comment]
> Ah, not the version of AGS, right? I misread...

Oh right, I see what you meant now. I only mean to match the release tag for the manual itself. How that relates to a specific release for AGS itself is not defined (but it could be).

**Comment by morganwillcock** [comment]
I'll close this for the moment. Hopefully the instructions won't change again for a while unless there are issues with the GitHub actions that are being used for the GitHub Pages or release uploads, everything else is pretty static and the same build steps can run locally if the CI falls apart.
